before_script:
  - npm install

test:
  image: node:latest
  stage: test
  script:
    - npm run test:unit
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml

pages:
  image: node:latest
  stage: deploy
  script:
    - npm run gitlab
    - mv public public-vue
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - master
